name: Code Quality Checks

on: [ pull_request ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  vitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: pnpm install
        env:
          CI: true
      - name: Run Tests
        run: pnpm test
        env:
          CI: true